name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"

      - name: run ls -la
        run: ls -al

      - name: pwd
        run: pwd

  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: find /
        run: find /
